### ISSUE TITLE
Enhancement: Would like to add dark mode

### ISSUE THREAD

**Issue by sachinggsingh** [GarimaSingh0109/Resum-Resume#1000]
Adding Dark mode to the Website will make it more Attractive and will give a bit more modern look as many website have that option

**Comment by shivaansh27** [comment]
would like to work on this issue,please assign this issue to me

**Comment by nikhilritgithub** [comment]
I really wanna work on this . please assign it to me

**Comment by sakshijain432** [comment]
I would like to work on this. please assign it to me
