### ISSUE TITLE
Add an input field for adding content to the resume in the build resume feature

### ISSUE THREAD

**Issue by akshaya-527** [GarimaSingh0109/Resum-Resume#1004]
when user want to add additional information about themselves which is not present in their linkedin we can add an input field such that they can give their own title and description
i would like to work on this please assign this to me

**Comment by shivaansh27** [comment]
would like to work on this issue please assign this to me

**Comment by AMOLJADHAV9** [comment]
hi @GarimaSingh0109   
you can assign me this issue i'll solve
