### ISSUE TITLE
Modify the Overall Look of the About Page

### ISSUE THREAD

**Issue by rishyym0927** [GarimaSingh0109/Resum-Resume#12]
Title: Modify the overall design of the About page to improve aesthetics

Description:
The current design of the About page looks outdated and unappealing. The following changes are necessary to enhance the aesthetics and user experience:

Redesign the layout for a more modern and professional look.
Improve typography, spacing, and alignment for better readability.
Add relevant images or icons to complement the text.
Ensure the page is responsive across all devices.
Apply animations or transitions using Framer Motion for a dynamic feel.

**Comment by GarimaSingh0109** [comment]
This issue is already assigned , look for new issues
