### ISSUE TITLE
Implement a Dark Mode Feature for the Website

### ISSUE THREAD

**Issue by rishyym0927** [GarimaSingh0109/Resum-Resume#13]
Title: Implement dark mode feature for the website

Description:
A dark mode feature should be added to the website to enhance user experience, especially for users who prefer low-light environments. The dark mode should:

Be toggleable with a clear switch or button.
Implement a visually pleasing color scheme for dark mode that aligns with the website’s design.
Ensure that all elements (text, buttons, images) are readable and accessible in dark mode.
Include smooth transitions when switching between light and dark modes.
Save the user's dark mode preference using local storage or cookies.

**Comment by Codewithmeowmeow** [comment]
Kindly assign me this issue i would love to work on it.

**Comment by t1nt1n-s0lv3r** [comment]
Kindly assign me this issue 
This would be my first contribution for gssoc and in open source in general as Im new

**Comment by meghanakn473** [comment]
can you please assign me this issue, i would like to work on it. And also i have worked on it before in my project.

**Comment by GarimaSingh0109** [comment]
whosoever will be providing better solutions first will be getting points

**Comment by rishyym0927** [comment]
can you switch the label and make it level3

**Comment by Codewithmeowmeow** [comment]
https://github.com/user-attachments/assets/26555fae-599b-43bd-95ac-5a40904da16e

Hey @GarimaSingh0109  i have completed this..kindly review:)
Also can u increase its level to 2
