### ISSUE TITLE
improving the navbar

### ISSUE THREAD

**Issue by NK-Works** [GarimaSingh0109/Resum-Resume#151]
![image](https://github.com/user-attachments/assets/12c7728f-e6a8-42fd-bf84-30a75c28df77)
improving the navbar overall...
ps: make sure to add the labels...
thansk:)

**Comment by sambedan1** [comment]
Plan:

Redesign the navbar layout for better organization and clarity, ensuring easy navigation.
Implement hover effects for better interactivity and to highlight active links.
Optimize the navbar for responsiveness, ensuring it functions well on mobile, tablet, and desktop devices.
Test the improved navbar across different browsers to ensure consistent performance.

**Comment by usha-here** [comment]
@NK-Works can I work on this issue of redesigning the navbar . Can you please assign this to me ?
