### ISSUE TITLE
Enhance Website Appearance with Favicon and UI Modifications.

### ISSUE THREAD

**Issue by snehhhcodes** [GarimaSingh0109/Resum-Resume#16]
My suggestion for improving the website would be to:

1.)   Adding a favicon to make the site visually professional in browser tabs.
2.)  Improving the landing page by adding a background image, adjusting text alignment, and updating the overall design for a more modern look.

Both the visual appeal and user experience would be much enhanced by this.

Please assign me to this issue, as I would like to take responsibility for this enhancement.

**Comment by hemanthhhhhh** [comment]
Would like to contribute. Please assign

**Comment by foreshubham** [comment]
I am interested in this issue. Can you please assign this to me.
