### ISSUE TITLE
Login Page Redesign

### ISSUE THREAD

**Issue by NK-Works** [GarimaSingh0109/Resum-Resume#185]
![image](https://github.com/user-attachments/assets/dbe56bd0-3d36-4782-a851-f1237965433a)
currently it looks very bad...
i can fix it...
make sure add the labels...
thanks:)

**Comment by Ananya-vastare** [comment]
I would like to solve this problem I am a gssoc contributor

**Comment by Khushi-51** [comment]
Login Page Redesign Proposal

Objective:
I propose redesigning the login page to enhance user experience and align with modern design standards.

Details:

Simplify the layout for a clean, user-friendly interface.
Improve the visual hierarchy with better typography and spacing.
Ensure responsiveness across devices, providing a seamless experience on mobile and desktop.
Add subtle animations (e.g., input field focus, button hover) for a more interactive feel.
I’m eager to take this on and will ensure the redesign maintains usability and performance.

Looking forward to your feedback!
