### ISSUE TITLE
Bug: Button Not Centered and Text Disappears on Hover

### ISSUE THREAD

**Issue by NikitaYewale007** [GarimaSingh0109/Resum-Resume#20]
**Description**
There are two issues affecting the buttons in the Ezyshop project:

Button Alignment: The button in the [specify the section, e.g., Hero section] is not centered properly, resulting in a misaligned appearance that affects the overall design.

Hover Text Disappearance: The text on the button in the Hero section disappears when hovered over, creating confusion for users and detracting from the user experience.

**Expected Behavior:**
The button should be centered within its container.
The button text should remain visible when the button is hovered over.

![Screenshot 2024-10-01 185848](https://github.com/user-attachments/assets/b4cd1496-01a3-4ce3-9e35-441bf891c141)

Actual Behavior:
The button is misaligned and not centered.
The button text disappears on hover.

**Comment by NikitaYewale007** [comment]
pls assign this task to me @GarimaSingh0109

**Comment by GarimaSingh0109** [comment]
@NikitaYewale007  this issue was created earlier and assigned you can look for the new one may be you can work on sign in page if you would like to do that the create an issue regarding the same follow the same structure of issue description you created here
