### ISSUE TITLE
The name can be changed to - Resume Rocket 🚀. And also needs a logo.

### ISSUE THREAD

**Issue by iamasraful** [GarimaSingh0109/Resum-Resume#221]
I can change the name to Resume Rocket 🚀. I will be more related to the purpose of the site. 

It could be the logo :

![Resume Rocket logo](https://github.com/user-attachments/assets/9af5f2d1-3d94-4b6b-a4a7-232c5970cfa0)

**Comment by GarimaSingh0109** [comment]
@iamasraful your logo is good but i didn't like the website name if you have any other suggestion do tell me as for logo you can work on it

**Comment by iamasraful** [comment]
Definitely I will work on it. And let you know another names as soon as possible.

**Comment by Jnanvesha04** [comment]
#221 please asign this issue to me

**Comment by ayush-py-c** [comment]
Can you assign this to me #221 I can work on it Can we use the name Enhancv

**Comment by iamasraful** [comment]
My issue not merged.
