### ISSUE TITLE
[Feature request]Improve Navigation in About Section And build resume section

### ISSUE THREAD

**Issue by Sanikaaher-19** [GarimaSingh0109/Resum-Resume#222]
Description:

The "About" section "Build Resume" section currently lacks clear and intuitive navigation, making it difficult for users to find the specific information they are looking for. This issue negatively impacts user experience and may lead to frustration.

The  navigation content  background design not same as home page 
![resume a-us issue](https://github.com/user-attachments/assets/79fa036f-bd69-4a42-b39b-c4bc554fc20e)
![resume issue2](https://github.com/user-attachments/assets/6432197e-18a2-4330-b79c-a7a75d9dfcdc)
 this   both are not similar

**Comment by Sanikaaher-19** [comment]
@Vaibhav22p-qw 
The abve issue i can solve can you assign me this issue? I am intrested to solve this issue

**Comment by GarimaSingh0109** [comment]
@Sanikaaher-19  @Sanikaaher-19 this issue is already solved
