### ISSUE TITLE
Add "Contact Us" menu at Navbar and create a different page for it.

### ISSUE THREAD

**Issue by Kratika-Solanki** [GarimaSingh0109/Resum-Resume#239]
As I have checked there is no contact section in this website only we are getting a option at the bottom but it will route to the home page when we click on that "contact us" option. I can correct this as well from my end.

**Comment by GarimaSingh0109** [comment]
@Kratika-Solanki start working on it

**Comment by Supraja-Gao** [comment]
please assign this issue to me also.

**Comment by Kratika-Solanki** [comment]
@GarimaSingh0109, could you please tell me the level of this issue?
