### ISSUE TITLE
Misaligned elements on the Login/SignUp page + No hover effects on buttons

### ISSUE THREAD

**Issue by agrwlAlOkIk** [GarimaSingh0109/Resum-Resume#243]
The text inputs for taking the user credentials and the buttons are misaligned, there's no constant spacing between the elements. No hover effects on the login/signup page buttons.

<img width="516" alt="Screenshot 2024-10-05 at 12 18 16 AM" src="https://github.com/user-attachments/assets/8fa2d033-038b-4193-86b3-935e152a5bfb">
<img width="519" alt="Screenshot 2024-10-05 at 12 17 59 AM" src="https://github.com/user-attachments/assets/272b7995-4e73-4bb4-b25d-50446a64c793">

I want to improve it by implementing the above changes, can you please assign it to me under Hacktoberfest and gssoc-ext.

**Comment by GarimaSingh0109** [comment]
@agrwlAlOkIk this issue is already solved you can work on another issue
