### ISSUE TITLE
BUG In home page

### ISSUE THREAD

**Issue by Prudhvi-232** [GarimaSingh0109/Resum-Resume#248]
I found a bug in the home page that there are two get started pages i would like to work on this issue . The task is to remove the extra template in home page
Please also add the GSSoC and Hacktoberfest labels to this issue
 
Here is the attachment of issue

https://github.com/user-attachments/assets/f3fd3e7f-9521-4334-b26b-f5cc4159d6e0

**Comment by GarimaSingh0109** [comment]
@Prudhvi-232 wait till you are assigned the issue for creating pr this is not ethical for now i m assigning you the issue but always follow code of conduct or will have to face consequences

**Comment by Prudhvi-232** [comment]
Thank you for assigning the issue. I sincerely apologize for the misunderstanding and any inconvenience caused. I will ensure to strictly follow the code of conduct moving forward and wait for proper assignment before proceeding.
