### ISSUE TITLE
Adding hover effects to "What our users say section"

### ISSUE THREAD

**Issue by komalnalage** [GarimaSingh0109/Resum-Resume#252]
Could you please assign me this task under the relevant tags for GSSOC-ext and Hacktoberfest-accepted? I’m confident this update will elevate the user interface and overall experience.

**Comment by GarimaSingh0109** [comment]
@komalnalage  always add ss of the issue 
for now start working on it

**Comment by biswajit-sarkar-007** [comment]
Hi, I'd like to work on this issue. Could you assign it to me?

**Comment by YOGINIMAHIMA1** [comment]
This issue needs to reopen it is not working
