### ISSUE TITLE
Enhancement of the footer section !!!

### ISSUE THREAD

**Issue by Abhi9shinde** [GarimaSingh0109/Resum-Resume#253]
@GarimaSingh0109 
-  The footer section still feels incomplete.
- It can be enhanced. The problem with the footer section is that the text becomes bright blue when hovered over the text, which is hard to read.
- Also, social media logos are comparatively smaller, and the hover effect is not that appealing.

![Screenshot 2024-10-05 115213](https://github.com/user-attachments/assets/362e1834-d655-4075-a665-d0e058fdef53)

- I would like to contribute for the enhancement of this
- Please give this a tag of gssoc-exd, hacktoberfest and I think this will be a level 2 problem

**Comment by GarimaSingh0109** [comment]
@Abhi9shinde THIS ISSUE IS already assigned look for some new issues
