### ISSUE TITLE
I want some changes in the front page to look more attractive

### ISSUE THREAD

**Issue by Dipanita45** [GarimaSingh0109/Resum-Resume#254]
![Screenshot 2024-10-05 120112](https://github.com/user-attachments/assets/2517b17a-f6dd-4b50-a50c-78a004c4923b)

**Comment by GarimaSingh0109** [comment]
@Dipanita45 start working on it

**Comment by Supraja-Gao** [comment]
please assign this issue to me. I would like to work on it

**Comment by Dipanita45** [comment]
I will start working on it
Thank you for giving me 😊

**Comment by DarakshanSaara** [comment]
Could you please assign this issue to me?
I can enhance it

**Comment by GarimaSingh0109** [comment]
@Dipanita45 this is not the right repo
