### ISSUE TITLE
Improving the UI of Footer

### ISSUE THREAD

**Issue by kanduru-abhiram** [GarimaSingh0109/Resum-Resume#255]
The footer feels a bit incomplete.

It can be enhanced better. We can add the Resum Resume(website name) in the footer section with a tagline for more good appearance and completes the footer.

![image](https://github.com/user-attachments/assets/896c77a5-e594-495b-9cc9-d0d64a1ec0d1)

I would like to contribute for the enhancement of the footer.

Kindly assign me this issue under Hacktoberfest 2024.

**Comment by GarimaSingh0109** [comment]
@kanduru-abhiram this issue is already assigned you can look for new issues
