### ISSUE TITLE
Adding the navbar in login/signup page

### ISSUE THREAD

**Issue by NK-Works** [GarimaSingh0109/Resum-Resume#266]
![image](https://github.com/user-attachments/assets/65a74e29-674d-4f24-b2c3-89e3f23ea809)
Currently no navbar here....
I can add that...
make sure to add the labels...
thanks...

**Comment by komalnalage** [comment]
Could you please assign me this task under relevant tags for gssoc-ext and hactoberfest-accepted  ?
Thank you!
