### ISSUE TITLE
Add a "Resume tips/guidance" section

### ISSUE THREAD

**Issue by riddhij0804** [GarimaSingh0109/Resum-Resume#267]
I would like to add a section that provides users with writing tips and guidelines for creating each section of their resume, such as how to write a strong professional summary, detail their work experience, and highlight their skills effectively.
I would love to work on this.
Could you please assign this issue me?
Looking forward to collaborating on this feature!

**Comment by riddhij0804** [comment]
@GarimaSingh0109 I am actively working on the "Resume Tips/Guidance" section and will be sharing the images of my progress very soon. Could you kindly assign a level to the issue at your convenience?
Looking forward to your response and continuing to contribute to the project!

**Comment by riddhij0804** [comment]
@GarimaSingh0109 **I have successfully completed making the resume tips section.**
Without hover:
![resum without hover](https://github.com/user-attachments/assets/3b4bb1b8-330c-4094-8e1e-55b25e85be90)
With hover:
![resum with hover](https://github.com/user-attachments/assets/c39b9499-7c09-42b1-b061-4d476ad9230a)
After scrolling:
![edu resum](https://github.com/user-attachments/assets/a22997ee-23a7-4f55-8750-0007ea1d0531)
I have added tips about writing the professional summary, educational details, skills, experience, achievements and some additional tips.
Moreover, I have added a hover effect.
**Would it be okay to submit a pull request for this issue now?
Looking forward to your feedback!**

**Comment by Akanshaku** [comment]
I would like to work on this issue pls assign me this @GarimaSingh0109
