### ISSUE TITLE
Update X[Twitter] Logo.

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [GarimaSingh0109/Resum-Resume#279]
## Description
I want to change the logo of X(formerly known as Twitter) which is added to your website in the footer section.

## Attachments
![image](https://github.com/user-attachments/assets/ba07b5c1-221e-4450-bc52-0ff44ade2d1f)

## Result
The updated X logo will be added to your website, removing ambiguity among the users.
![image](https://github.com/user-attachments/assets/b5d2cd0e-eaba-476f-a827-99911bebab62)

**Comment by Antima2004** [comment]
Please assign this to me as i updated twitter logo on other repository yesterday . Please add level1 label  under gssoc

**Comment by rajdeepchakraborty-rc** [comment]
@GarimaSingh0109 can you please review the issue and assign me?
