### ISSUE TITLE
 On Login page: Footer Overlaps and Covers the Login Box

### ISSUE THREAD

**Issue by Palmistry2310** [GarimaSingh0109/Resum-Resume#282]
On the login page, the current size of the footer is too large, causing it to overlap and partially cover the login box. This affects the visibility of the login form and creates a poor user experience. I would like to work on to improve the visibility of the login box. This will ensure that the login form is fully accessible to users.

@GarimaSingh0109 May you please assign this issue to me under the labels: gssoc-ext, hacktober-accepted and level? I am confident that I can implement a solution that enhances the user experience.

![login page issue](https://github.com/user-attachments/assets/b7d7573a-9963-46e2-b7d1-f7ff98e67c1a)

**Comment by Mirnalkishor** [comment]
I want to work on this issue.please assign this me.
