### ISSUE TITLE
In Our Features section : Images in cards are too Small – Adjust Image Size for Better Visibility.

### ISSUE THREAD

**Issue by Palmistry2310** [GarimaSingh0109/Resum-Resume#286]
The images displayed in the cards in the ' our features' section are currently too small, resulting in poor visibility and a diminished user experience. The image size should be adjusted to fit better within the card layout, providing clearer visuals.
 @GarimaSingh0109 I request you to assign this issue to me, as I would like to fix the image sizing for better user experience.
![image in card](https://github.com/user-attachments/assets/7c394d69-dcc3-4e16-ae11-3a69f97aa072)

**Comment by 8tool** [comment]
I would like to work on this, I am new here and would like to contribute too, I see that  someone else is working on it , @Palmistry2310, would like to be part of it too

**Comment by 8tool** [comment]
Is 24x7 Support a Tempate if so can we delete it ? are we providing the service ?
