### ISSUE TITLE
Bug: Button Not Centered and Text Disappears on Hover

### ISSUE THREAD

**Issue by NikitaYewale007** [GarimaSingh0109/Resum-Resume#29]
### Description:
There are two issues affecting the buttons in the Resume project:

**Button Alignment: The button in the [specify the section, e.g., Hero section] is not centered properly, resulting in a misaligned appearance that affects the overall design.**

**Hover Text Disappearance: The text on the button in the Hero section disappears when hovered over, creating confusion for users and detracting from the user experience.**

### Expected Behavior:
The button should be centered within its container.
The button text should remain visible when the button is hovered over.

![Screenshot 2024-10-01 185848](https://github.com/user-attachments/assets/716b935e-9b99-4342-850a-78b2febda3c4)

Actual Behavior:
The button is misaligned and not centered.
The button text disappears on hover.

### could you pls assign this task to me @GarimaSingh0109

**Comment by SanikaBhalerao1345** [comment]
hi @NikitaYewale007 i would like to work and solve this issue.pls assign it to me

**Comment by Gaurav075** [comment]
@NikitaYewale007 I would like to work on this project.Pls assign it to me

**Comment by GarimaSingh0109** [comment]
This issue has already been done you can work on build resume page
