### ISSUE TITLE
Remove "Build Resume" Link from resume.html

### ISSUE THREAD

**Issue by ShashankDahake7** [GarimaSingh0109/Resum-Resume#30]
Description:
The "Build Resume" link in the navigation bar currently routes back to the same page (resume.html), which creates unnecessary redundancy and confusion for the user. Since the user is already on the "Build Resume" page, having a link that routes back to the same page doesn't add value to the user experience.

Before:(Issue)
![gsoc3](https://github.com/user-attachments/assets/42395d0b-39fb-479c-a2d4-d8cffa36ff29)

After:(Solution)
![gsoc4](https://github.com/user-attachments/assets/dd274fb9-195e-4740-8c42-ad607f05ef1b)

**Comment by meghanakn473** [comment]
can you please assign me this issue, i want to work on it.

**Comment by hemanthhhhhh** [comment]
Would love to contribute and remove the build resume from the navigation and please add hacktoberfest label
