### ISSUE TITLE
About page re-design with include of contact details

### ISSUE THREAD

**Issue by anish013326** [GarimaSingh0109/Resum-Resume#32]
The About Page re-design focuses on providing a clear, welcoming introduction to your open-source project while offering essential information about your vision, team, and what the project offers. It includes a streamlined layout that highlights the project’s goals, core values, and key features, alongside an easy-to-navigate section for contact details.

![Screenshot 2024-10-01 193202](https://github.com/user-attachments/assets/d4c37ce7-ea62-4d8b-8c32-9b51d49bf9aa)

**Comment by hemanthhhhhh** [comment]
Please assign this issue to me and label it as hacktoberfest

**Comment by foreshubham** [comment]
Let me solve this issue for you. Please assign this to me and mark it as hacktoberfest, gssoc.

**Comment by GarimaSingh0109** [comment]
@anish013326 @hemanthhhhhh @foreshubham this is issue has already been done by someone else try to work on making the website functional rather than just designing as you can get more points on that
