### ISSUE TITLE
ADD  Readme file 

### ISSUE THREAD

**Issue by sahhoArjun097** [GarimaSingh0109/Resum-Resume#328]
### Issue Description

Description: The README file needs updates to reflect the current status and features of the project. This includes:

Project Overview: Provide a brief description of the project.

Installation Instructions: Include clear steps for setting up the project locally.

Usage: Add examples of how to use the main features.

Contributing Guidelines: Outline how others can contribute to the project.

License Information: Specify the license under which the project is distributed.

### Checklist

- [X] I have checked the existing [issues](https://github.com/GarimaSingh0109/Resum-Resume/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/GarimaSingh0109/Resum-Resume/blob/main/CONTRIBUTING.md)
- [x] I am willing to work on this issue (optional)

**Comment by sahhoArjun097** [comment]
can you provide me some details with i need to do add in readme file

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.
