### ISSUE TITLE
[Mention The Feature]: Add Website Views Widget in the footer

### ISSUE THREAD

**Issue by rohitinu6** [GarimaSingh0109/Resum-Resume#333]
### Is your feature request related to a problem? Please describe.

To count and display the no of views, this website is getting

### Describe the solution you'd like.

I would like to add a website views widget that will display the no of views this website is getting and gets updated automatically, when someone is landed on this website

### Additional context.

@GarimaSingh0109 , please assign this issue to me and do add the gssoc and hacktoberfest labels

### Show us the magic with screenshots

A prototype of the Website Views Widget is as follows:

![image](https://github.com/user-attachments/assets/10158bdd-88e9-4d39-8513-cc2225960190)

### Checklist

- [X] I have checked the [Existing Issues](https://github.com/GarimaSingh0109/Resum-Resume/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/GarimaSingh0109/Resum-Resume/blob/main/CONTRIBUTING.md)
- [X] I want to work on this issue. (optional)

**Comment by GarimaSingh0109** [comment]
@rohitinu6 follow the code of conduct do not create the pr before issue is assigned
