### ISSUE TITLE
Footer is not placed at the bottom properly 

### ISSUE THREAD

**Issue by hadifarousheen** [GarimaSingh0109/Resum-Resume#370]
The footer should be placed at the bottom of the website. I will fix the position of footer by placing at the bottom.
![Screenshot_20241007-162346_Chrome](https://github.com/user-attachments/assets/46021aea-8213-42b0-afaa-b2e3dd9cd6e0)

Please assign me this issue @GarimaSingh0109

**Comment by Vipul-Ydv** [comment]
is it still available ?

**Comment by Vipul-Ydv** [comment]
hey i've fixed the issue please assign me

**Comment by Akanshaku** [comment]
I would like to work on this issue pls assign me this @GarimaSingh0109
