### ISSUE TITLE
Improve register page 

### ISSUE THREAD

**Issue by karthik120710** [GarimaSingh0109/Resum-Resume#373]
I have seen on the register page that the that the power of the resume builder bar is interrupting the full details. I would like to remove that bar and make register details on a separate page and sign in on a separate page.
<img width="1440" alt="Screenshot 2024-10-07 at 4 24 45 PM" src="https://github.com/user-attachments/assets/4ced37a9-00d5-41ab-a689-f36adc51d0fc">

**Comment by karthik120710** [comment]
@GarimaSingh0109  can you assign this issue for me I have set the code base on my local machine

**Comment by GarimaSingh0109** [comment]
This issue does not exist any longer try looking for new issues
