### ISSUE TITLE
Home page is repeated 

### ISSUE THREAD

**Issue by Hemraj-7** [GarimaSingh0109/Resum-Resume#375]
Resum-Resume Website home page is repeated two times

I want to fix it, assign me

Add gssoc-ext , hactoberfast-accepted and level 3 labels

![Screenshot 2024-10-07 165750](https://github.com/user-attachments/assets/e0d313f0-c8d4-41dd-9170-ee68d0752ebe)

**Comment by Sawan-Kushwah** [comment]
Please assign me i want to work on this I will write well maintained and clean code and good UI

**Comment by GarimaSingh0109** [comment]
There is no such issue in website

**Comment by Hemraj-7** [comment]
> There is no such issue in website

Yeah, now it is working good. but when i was fork then it is repeated home page
