### ISSUE TITLE
improve the ui of build resume 

### ISSUE THREAD

**Issue by RiyaJain8114** [GarimaSingh0109/Resum-Resume#441]
enhance the ui of build resume as the input box and and headers are not properly aligned 
![image](https://github.com/user-attachments/assets/449e180a-ec31-4034-8a15-98f88eb61a88)

**Comment by ChetanReddy1303** [comment]
Hey @RiyaJain8114 could you please review my PR #452 

![Screenshot 2024-10-10 163946](https://github.com/user-attachments/assets/22314f2b-2a9e-4892-947b-4adbae0a1509)

**Comment by ChetanReddy1303** [comment]
Made the same navbar changes in about page too

**Comment by GarimaSingh0109** [comment]
Discussed in #269
