### ISSUE TITLE
UX Modification 

### ISSUE THREAD

**Issue by Peart-Guy** [GarimaSingh0109/Resum-Resume#457]
Footer not readable
![image](https://github.com/user-attachments/assets/7f093b12-4d48-4585-bc6f-f791aa966715)

**Comment by GarimaSingh0109** [comment]
@Peart-Guy refer this #460

**Comment by Peart-Guy** [comment]
@GarimaSingh0109  
Kindly check the PR.
As you have not given me the Labels of GSSOC-24 EXTD , hacktoberfest , Level in the pull request.
I have been asking for it so many days 
PR: #468 
PR Link : https://github.com/GarimaSingh0109/Resum-Resume/pull/468
