### ISSUE TITLE
LOGIN PAGE NOT WORKING AND IMPROVEMENT OF SIGNUP PAGE 

### ISSUE THREAD

**Issue by HS202022** [GarimaSingh0109/Resum-Resume#458]
I WANT TO REMOVE THE LOGIN PAGE AND ADD BOTH LOGIN AND SIGN UP IN ONE PAGE 
![Screenshot 2024-10-10 181401](https://github.com/user-attachments/assets/4c681652-00ba-4a04-be1f-77c4999b6f4c)
![Screenshot 2024-10-10 181349](https://github.com/user-attachments/assets/892cf519-8830-4fe8-95a0-bbb91832bd22)
SAMPLE OF WHAT I CAN MAKE 

https://github.com/user-attachments/assets/8e19bac1-ed07-4d41-b162-573f42040010

**Comment by GarimaSingh0109** [comment]
@HS202022 you can start working on it but follow the color pallet

**Comment by HS202022** [comment]
yeah

**Comment by HS202022** [comment]
I think there were changes after I pushed it let me resolve it then
