### ISSUE TITLE
RESUME

### ISSUE THREAD

**Issue by Swyom** [GarimaSingh0109/Resum-Resume#459]
YOUR INTERFACE IS NOT LOOKING GOOD SOME PADDINGS ARE REQUIRED AND ALSO YOUR LOGIN PAGE IS NOT WORKING PROPERLY ,BUTTON ALSO .

**Comment by Swyom** [comment]
GIVE ME A CHANCE TO FIX IT

**Comment by GarimaSingh0109** [comment]
@Swyom discussed in #460
