### ISSUE TITLE
BUG: Privacy Policy Page Missing

### ISSUE THREAD

**Issue by Priyank00007** [GarimaSingh0109/Resum-Resume#489]
I want to create a privacy policy page so that to enhance the website

**Comment by GarimaSingh0109** [comment]
@Priyank00007 refer #269

**Comment by GarimaSingh0109** [comment]
@Priyank00007 do follow the color pallet

**Comment by Priyank00007** [comment]
> @Priyank00007 do follow the color pallet

Sure mam

**Comment by Roshn1** [comment]
Hi , I came across this issue  and found it aligns with my skills and interest. I am confident I can contribute effectively to this issue.
Would you mind assigning it to me so I can start working on it? Looking forward to contributing and adding value to the project.

**Comment by byteom** [comment]
please assign this task to me.

**Comment by Priyank00007** [comment]
> Hi , I came across this issue  and found it aligns with my skills and interest. I am confident I can contribute effectively to this issue.
> Would you mind assigning it to me so I can start working on it? Looking forward to contributing and adding value to the project.

It's been already assigned to me and also I hv created the PR

**Comment by Priyank00007** [comment]
> please assign this task to me.

It's been already assigned to me and I have already sent the PR
