### ISSUE TITLE
There is a typo error in home page!

### ISSUE THREAD

**Issue by 2004pra** [GarimaSingh0109/Resum-Resume#498]
As you can see there is typo error in the highlighted text where letter 'a' should not be capital
Please assign me this task under gssocextd , hactoberfest  !
this is my first time doing the contrubition so i am trying with basics like typ error .
@GarimaSingh0109 
![Screenshot 2024-10-11 235727](https://github.com/user-attachments/assets/a8be4bdb-b240-4842-80dd-d7b3ab8dd55f)

**Comment by ambarmishraa** [comment]
Assign me this task
