### ISSUE TITLE
Create README.md file

### ISSUE THREAD

**Issue by rishyym0927** [GarimaSingh0109/Resum-Resume#5]
Issue 1: Create README.md file
Title: Create README.md file for the project

Description:
A detailed README.md file needs to be created to provide an overview of the project, setup instructions, and guidelines for contributors. The README.md should include:

Project introduction and purpose.
Features of the project.
Installation and setup guide.
Usage instructions.
Links to relevant documentation.
Contribution guidelines.
License information.

**Comment by GarimaSingh0109** [comment]
@rishyym0927 Contact me personally so that i can help you with this issue

**Comment by rishyym0927** [comment]
please add the gssoc-extd label in it
