### ISSUE TITLE
CONTRIBUTING.md file for the project

### ISSUE THREAD

**Issue by rishyym0927** [GarimaSingh0109/Resum-Resume#6]
Issue 2: Create CONTRIBUTING.md file
Title: Create CONTRIBUTING.md file for the project

Description:
A CONTRIBUTING.md file should be added to the project to guide developers on how to contribute effectively. This file should include:

Steps to fork the repository.
Instructions for setting up the development environment.
Guidelines for submitting issues and pull requests.
Coding style and best practices.
Information on how to run tests (if applicable).
Code of conduct for contributors.

**Comment by hemanthhhhhh** [comment]
Please assign this to me. Would love to contribute
