### ISSUE TITLE
 Footer Section Links for CV Templates Not Working

### ISSUE THREAD

**Issue by snehhhcodes** [GarimaSingh0109/Resum-Resume#670]
# Current Behavior:
The footer section of the website includes link for CV templates, but  link does not redirect users to any specific page or content. As a result, users are unable to access the CV templates directly from the footer.

# Proposed Enhancement:
To improve user experience and provide better access to CV templates, I would like to create a separate page dedicated to displaying CV templates. This new page will feature containers showcasing various CV templates that users can click on. Upon clicking a template, it will enhance to display a larger view, allowing users to explore different design ideas effectively.

# Expected Outcome:
By implementing this feature, users will have direct access to a variety of CV templates, enabling them to gather inspiration and ideas for their own resumes. This will enhance the overall usability of the website and provide a valuable resource for users seeking CV design ideas.

# Priority: Medium

**Comment by snehhhcodes** [comment]
@GarimaSingh0109 please review this issue once and assign it to me if suitable

**Comment by ambarmishraa** [comment]
Assign me this task.!
