### ISSUE TITLE
Improve Header Component

### ISSUE THREAD

**Issue by rishyym0927** [GarimaSingh0109/Resum-Resume#7]
Issue 3: Improve Header Component
Title: Improve Header Component with enhanced design and functionality

Description:
The current header component needs improvements in both design and functionality. The following changes are required:

Add responsiveness to ensure the header looks good on all screen sizes.
Improve the visual design with better spacing, fonts, and color palette.
Ensure smooth transitions and hover effects.
Add an animated logo or any other brand elements using Framer Motion for a polished look.
Refactor the code to make it more maintainable and readable.

**Comment by GarimaSingh0109** [comment]
@rishyym0927 TRY ADDING THE SS OF THE ISSUE IT WILL BE HELPFUL FOR U AS WELL AS PA's

**Comment by hemanthhhhhh** [comment]
Please assign this to me. Would love to contribute

**Comment by rishyym0927** [comment]
please add label gssoc-ext so i can work on it
