### ISSUE TITLE
🐛BUG : Sign Up page - Name field validation

### ISSUE THREAD

**Issue by akash70629** [GarimaSingh0109/Resum-Resume#703]
### Description

The "Name" field on the **_Sign Up_** page should only accept alphabetical letters (a-z, A-Z). Currently, the field allows users to input symbols and special characters, which may lead to invalid or spam submissions.

### Steps to Reproduce

1. Go to SignUp page
2. Click on Name field and type numbers and symbols.
3. See there is no error message.

### Expected Behavior

The "Name" field in the Sign Up Page should only accept alphabetical letters (a-z, A-Z).

### Actual Behavior

Currently, the field allows users to input symbols and special characters, which may lead to invalid or spam submissions.

### Screenshots

![image](https://github.com/user-attachments/assets/ecbc1678-6ac1-47ec-ab68-a700e587b6cd)

### What browser are you seeing the problem on?

- [X] Chrome

### Checklist

- [X] I have checked the [existing issues](https://github.com/aditya-bhaumik/Pathsphere/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/aditya-bhaumik/Pathsphere/blob/main/contributing.md)
- [X] I want to work on this issue. (optional)

**Comment by ambarmishraa** [comment]
Assign me this task.!
