### ISSUE TITLE
Improve Hover Effect on "Get Started" Button

### ISSUE THREAD

**Issue by neeru24** [GarimaSingh0109/Resum-Resume#708]
The current hover effect on the "Get Started" button shows black text that fades with the background color, resulting in a lack of noticeable difference. This makes it difficult for users to see the button's hover state, reducing visual clarity and engagement.

**Proposed Changes:**

- Change the text color to white when the "Get Started" button is hovered over.
- Ensure that the background color remains consistent to create a strong contrast with the white text.

![image](https://github.com/user-attachments/assets/a3432bad-0d01-42f4-af49-9024ff19c971)

**Comment by MuhammadZaid-31** [comment]
Hey @GarimaSingh0109 ,
i would like to work on the issues , please assign me the issues
