### ISSUE TITLE
adding dark mode 

### ISSUE THREAD

**Issue by ShrishtiSingh26** [GarimaSingh0109/Resum-Resume#71]
I would like to add the feature to change theme of the website from light to dark mode and vis-a-versa 
Can you please assign me this issue

**Comment by ShrishtiSingh26** [comment]
i would like to work on this issue

**Comment by sanikadesai76** [comment]
I am a contributor participating in the GirlScript Summer of Code 2024 - Extended Edition.
I would like to work on Issue #71: Adding Dark Mode. After reviewing the website, I believe adding a dark theme can greatly enhance the user experience, especially for those who prefer a darker interface or browse at night.

**Comment by ShrishtiSingh26** [comment]
Will be more happy if you assign the issue to the person who raised it? Therefore Please assign the issue to me so that I can contribute successfully.
