### ISSUE TITLE
The 'Resume Resume' project name on the site is not redirecting to the homepage of the website when clicked.

### ISSUE THREAD

**Issue by Sandigupta** [GarimaSingh0109/Resum-Resume#724]
Let me add this feature. To improve users experience.
![Screenshot 2024-10-19 011454](https://github.com/user-attachments/assets/541fa084-dc7e-4ce8-b423-ee3c82d48312)

**Comment by Sai-Dangade777** [comment]
addressed the same issue the very moment i saw the website !
