### ISSUE TITLE
[Feat]: Change the color of text in footer section.

### ISSUE THREAD

**Issue by Adityadhiman0** [GarimaSingh0109/Resum-Resume#725]
I want to change the color of text in footer section because text color is dull, which causes the poor visibility of text.
![Screenshot 2024-10-19 012932](https://github.com/user-attachments/assets/12feae5f-3c47-4e6c-9c6e-ba01889bd2ed)

**Comment by aryan3665** [comment]
i want to change the color as well as fonts in it and in header part make it more eye cachy ,kindly asign it to me me with the tag hacktoberfest and gssoc-extd

**Comment by amiya-cyber** [comment]
i want to change the color as well as fonts in it and in header part make it more eye cachy ,kindly asign it to me me with the tag hacktoberfest and gssoc-extd

**Comment by amiya-cyber** [comment]
I want to change the color of text in footer section because text color is dull, which causes the poor visibility of text.,kindly asign it to me me with the tag hacktoberfest and gssoc-extd

**Comment by Adityadhiman0** [comment]
Please assign this issue to me So i could Fix it as soon as possible.
