### ISSUE TITLE
Add Signup and Login Page to the Website

### ISSUE THREAD

**Issue by sahhoArjun097** [GarimaSingh0109/Resum-Resume#731]
We need to implement a user authentication system with signup and login pages similar to the example provided. The design should include the following:

A login form with fields for "Username or Email" and "Password."
"Forgot password?" link for password recovery.
Option for users to log in using Google, LinkedIn, GitHub, or Facebook.
A "Remember me" checkbox.
A button for users who don't have an account to sign up.
Signup page should have relevant fields (e.g., name, email, password) and similar social login options.

**Comment by Hafsa-shoaib989** [comment]
@GarimaSingh0109 can you please assign this task to me ? as its been 2 weeks , which is why i am asking
