### ISSUE TITLE
footer issue

### ISSUE THREAD

**Issue by dipeshkumar799** [GarimaSingh0109/Resum-Resume#749]
footer is in flex position it is not looking good..i make the footer good to make it flex.

![Screenshot (83)](https://github.com/user-attachments/assets/75cf4129-db22-4053-9f7a-e251b05eb178)
@GarimaSingh0109 :plse assign me

**Comment by MuhammadZaid-31** [comment]
Hey @GarimaSingh0109 
I would like to work on these ,kindly assign me the issue
