### ISSUE TITLE
[FEAT]: Adding Dark Mode Functionality

### ISSUE THREAD

**Issue by JHA-geek-AYUSH** [GarimaSingh0109/Resum-Resume#778]
## Feature Request: Dark Mode Functionality

Hi @GarimaSingh0109,

I would like to implement a **Dark Mode** feature for the website.

### Feature Description:
Dark Mode allows users to switch the website's color scheme from light to dark, providing a more comfortable viewing experience in low-light environments. It will also give the website a modern and accessible feel.

### Benefits:
- **Reduces eye strain** for users in dim environments.
- **Improves accessibility** for users sensitive to bright screens.
- Provides a **modern user interface** that appeals to a wide range of users.

### Implementation:
- Add a toggle switch in the UI for users to switch between light and dark modes.
- Ensure **color contrast** and **readability** are maintained in both modes.

**Comment by Hafsa-shoaib989** [comment]
@GarimaSingh0109 can you please assign this task to me ? as its been one week , which is why i am asking

**Comment by Hafsa-shoaib989** [comment]
@GarimaSingh0109 ??
