### ISSUE TITLE
[⭐FEATURE] Add a Translation Tool (all language) ✨

### ISSUE THREAD

**Issue by Subhajit-2023-44** [GarimaSingh0109/Resum-Resume#780]
I want to add a Translation Tool(all language) properly.

@GarimaSingh0109 PA please assign me this task.

![Screenshot 2024-10-20 211754](https://github.com/user-attachments/assets/56b892e5-f4bc-4a18-abd9-e1e63f17afb9)

**Comment by Subhajit-2023-44** [comment]
@GarimaSingh0109

**Comment by Subhajit-2023-44** [comment]
@GarimaSingh0109

**Comment by charmi2109** [comment]
Please assign me this issue @GarimaSingh0109
