### ISSUE TITLE
[✨FEATURE] Add a ChatBot Assistant

### ISSUE THREAD

**Issue by Subhajit-2023-44** [GarimaSingh0109/Resum-Resume#781]
I want to add a ChatBot Assistant..

@GarimaSingh0109  please assign me this task.

![Screenshot 2024-10-20 211754](https://github.com/user-attachments/assets/52bfae92-05cc-4e6a-b5e2-87164c91ab76)

**Comment by Subhajit-2023-44** [comment]
@GarimaSingh0109

**Comment by Varshatm218** [comment]
Assign this to me under GSSoC-extd

**Comment by Subhajit-2023-44** [comment]
@GarimaSingh0109
