### ISSUE TITLE
Improve the Login page

### ISSUE THREAD

**Issue by Himanshu-kumar025** [GarimaSingh0109/Resum-Resume#788]
Login page is not looking good . I like to improve the whole login page  under GSSOC'24 and Hacktofest'24
thank you
![Screenshot 2024-10-20 224547](https://github.com/user-attachments/assets/d0702a14-2fe8-4458-9fcd-801c8881bb24)

**Comment by MuhammadZaid-31** [comment]
I would like to work on this kindly assign me the issues hussainzaid987@gmail.com
