### ISSUE TITLE
Add Icons to Every Page 

### ISSUE THREAD

**Issue by AnushkaChouhan25** [GarimaSingh0109/Resum-Resume#795]
Add the three icons shown in the attached image to every page of the website for quick access.

1. Fix Suggestions:
 - Position: Place the icons in a fixed position for accessibility from anywhere on the site.
 - Design: Ensure the icons are styled consistently with the theme.
2. Functionality:
 - Icons should be clickable and redirect to relevant pages or actions.
 - Add hover effects or slight animations to improve interactivity.
3. Responsiveness: Icons should adjust properly for mobile and desktop views.
4. Accessibility: Include aria-labels and ensure icons are screen-reader-friendly.

![image](https://github.com/user-attachments/assets/01b74590-6fc5-4a29-b9ee-2ba17270c155)

**Comment by devrupchowdhury** [comment]
I want to work on this , please assign me this ..
