### ISSUE TITLE
Improve Footer Component

### ISSUE THREAD

**Issue by rishyym0927** [GarimaSingh0109/Resum-Resume#8]
Description:
The footer component requires enhancements to improve both the user experience and accessibility. The improvements should include:

Ensure the footer is responsive across various devices.
Add accessible links and icons for social media and other resources.
Improve the layout for better structure and readability.
Apply hover effects and animations for interaction.
Ensure the footer meets accessibility standards (ARIA attributes, focus management).

**Comment by Inija-2503** [comment]
Please assign me this issue i would like to work on it

**Comment by rishyym0927** [comment]
please add the label gssoc-extd
