### ISSUE TITLE
 Footer Redirecting Links Not Working

### ISSUE THREAD

**Issue by VidhanThakur09** [GarimaSingh0109/Resum-Resume#800]
### Description
The footer links on the website are not functioning as intended. When clicked, they do not redirect users to the corresponding pages or sections. This issue is impacting user navigation and accessibility.

### Use Case
The footer links are essential for users to quickly access important information or navigate to specific sections of the website. They are particularly useful for users who may be unfamiliar with the site's structure or want to find information about the company, contact details, or other resources.

### Benefits
**Resolving this issue will:**

- Improve user experience by ensuring that footer links are functional and provide a seamless navigation experience.
- Enhance website accessibility by making it easier for users to find information and navigate the site.
- Boost user confidence and satisfaction by demonstrating a commitment to maintaining a well-functioning and user-friendly website.

https://github.com/user-attachments/assets/cf8813d6-a98d-417a-85bd-14b794dcc844

@GarimaSingh0109 can you assign this issue to me with labels "gssoc-ext" with levels and "hacktoberfest-accepted";

**Comment by GarimaSingh0109** [comment]
@VidhanThakur09 this issue is already assigned
