### ISSUE TITLE
improvising the footer for better readability and adding hover effect on cards (what our users say)

### ISSUE THREAD

**Issue by anshxika** [GarimaSingh0109/Resum-Resume#801]
the footer text colors are all mixing with the background which makes is hard to read plus degrades the user experience. in addition of that hover effect can be added on the rest of the cards to make it look more better

https://github.com/user-attachments/assets/81c6067c-158f-4d32-8cbd-7490302d45d1

@GarimaSingh0109 let me fix it and please assign it to me under hacktoberfest and gssoc-ext
thanks

**Comment by Symbiote07** [comment]
@GarimaSingh0109 assign me this issue , I will solve it as soon as possible

**Comment by charmi2109** [comment]
please assign me this issue, I will work on it and make website more appealing @GarimaSingh0109
