### ISSUE TITLE
Login page not displayed properly

### ISSUE THREAD

**Issue by Ankitha2130** [GarimaSingh0109/Resum-Resume#803]
![image](https://github.com/user-attachments/assets/fcc67677-1c4c-4ab8-b433-02eb337c1b0a)

I would like to work on the login page. Please assign this issue to me under gssoc-ext, and a suitable labels.

**Comment by Muralidhar216** [comment]
Assign me this task

**Comment by neetu20221** [comment]
can  you assign this issue to me
