### ISSUE TITLE
Clicking on "ResumResume" logo should redirect to the home page

### ISSUE THREAD

**Issue by tejasam571** [GarimaSingh0109/Resum-Resume#807]
**Description:**
**Problem:**
Currently, clicking on the "ResumResume" logo in the website header does not redirect the user back to the home page as expected. This can be an inconvenience for users who want to quickly navigate back to the home page.

**Expected Behavior:**
When the user clicks on the "ResumResume" logo, they should be redirected to the home page of the website, providing a smoother navigation experience.

**Proposed Solution:**
Add a clickable link to the "ResumResume" logo in the website's header.
Ensure that the link correctly navigates to the root/home URL of the site.
Test on different browsers and devices to confirm consistent behavior.
**Additional Context:**
This feature is a standard practice across websites to allow users an easy way to return to the main page, improving user experience.

![Screenshot 2024-10-21 202459](https://github.com/user-attachments/assets/bbdf7d50-c0e4-4ce6-ad1b-f3cce8c357b9)

**Comment by tejasam571** [comment]
@GarimaSingh0109  , I'm a GSSOC-Ext and Hacktober Fest CONTRIBUTOR !

**Comment by charmi2109** [comment]
Please assign me this issue! I want to work on it @GarimaSingh0109
