### ISSUE TITLE
Add Feature to Download Resume as PDF

### ISSUE THREAD

**Issue by Mohitranag18** [GarimaSingh0109/Resum-Resume#808]
### Description:

I would like to request the addition of a feature to allow users to download their generated resume as a PDF file by clicking a "Download" button. This feature will enhance the existing resume builder by providing a seamless method for users to save their resume in PDF format directly from the browser.

### Feature Breakdown:

- Download Button
- html2pdf Integration
- PDF Generation Process
- Styling and Responsiveness

**Comment by sourav349** [comment]
Hey,@GarimaSingh0109 I am interested in this issue, can you assign this too me.. I believe these changes will significantly enhance the overall user experience. Thank you!

1.Preview Before Download: Allow users to preview the PDF before downloading, perhaps in a modal, to ensure they are satisfied with the layout and content.
2.Download Options: Provide options for different file formats (e.g., DOCX) in addition to PDF, catering to various user preferences.
3.User Feedback: Implement a feedback mechanism after the download, asking users if they encountered any issues or have suggestions for improvement.
4.Loading Indicator: Include a loading indicator when the PDF is being generated to keep users informed and reduce uncertainty during the process.
5.Accessibility Features: Ensure the download button and process are accessible, with appropriate ARIA labels and keyboard navigation support.
6.Mobile Optimization: Test and optimize the download process specifically for mobile users, ensuring a seamless experience on smaller screens.
