### ISSUE TITLE
Improve Footer and Navbar Styling on About Page

### ISSUE THREAD

**Issue by Mohitranag18** [GarimaSingh0109/Resum-Resume#810]
### Description:

The current footer and navbar styling on the About page is inconsistent and needs improvement. The design does not align well with the rest of the page, and certain elements are misaligned or improperly styled.

### Feature Breakdown:

**Navbar Improvements:**
Fix alignment issues and improve spacing between navigation elements.
Ensure responsive design for all screen sizes.
Apply consistent styling to match the project's overall design (fonts, colors, hover effects).

**Footer Improvements:**
Adjust the layout for better structure and alignment of footer elements (social media links, copyright text, etc.).
Ensure the footer is responsive and looks clean across different devices.
Match the design language of the rest of the site (consistent color, fonts, spacing).

**Comment by sahilsama** [comment]
i want to work on this issue, please assign it to me!

**Comment by sahilsama** [comment]
so are you working on this issue?

**Comment by Mohitranag18** [comment]
Yes brother

**Comment by sahilsama** [comment]
achaa got it got it!
