### ISSUE TITLE
Proposal to Fix Syntax Errors in index.html

### ISSUE THREAD

**Issue by Palmistry2310** [GarimaSingh0109/Resum-Resume#812]
I noticed several syntax errors in the index.html file that may affect the proper functioning . I would like to contribute by addressing these issues to ensure this file adheres to best practices and is error-free.
![Screenshot 2024-10-21 224617](https://github.com/user-attachments/assets/42a758da-d2a8-4b1c-8c1f-2dbd6382f2aa)

Identified Issues:

Missing semicolons .
Duplicate value assignments leading to confusion.
Incomplete CSS blocks due to missing closing braces.
Unnecessary text that should be removed.

Proposed Solutions:

I propose to:
Review the entire index.html file for missing semicolons.
Remove duplicate value assignments for clarity.
Add missing closing braces where needed.
Eliminate unwanted text in the file.
Optimize and clean up redundant CSS to improve performance.

**Comment by Hafsa-shoaib989** [comment]
@GarimaSingh0109 can you please assign this task to me ? as its been one week , which is why i am asking
