### ISSUE TITLE
Footer design in Home page

### ISSUE THREAD

**Issue by SumaLatha2023** [GarimaSingh0109/Resum-Resume#817]
The footer section in the home page has improper look as per UI.
The background colors of the footer sections are not visually appealing, as there is a noticeable contrast between the lighter purple and the dark background, making the text difficult to read. Additionally, the layout of the footer could use better spacing and alignment to enhance readability and overall design coherence.

![Screenshot 2024-10-20 191702](https://github.com/user-attachments/assets/f07848c9-713e-4998-b3cf-f67999780be0)

I want to redesign this and enhance the footer design.

**Comment by Lokesh-Mapui** [comment]
I would like to work on this project,please assign it to me.I am confident that my skills and experience will add value to the project

**Comment by neetu20221** [comment]
can u assign this task to me
