### ISSUE TITLE
Colour Scheme of the Overall website and Text sizing issue

### ISSUE THREAD

**Issue by Mohitranag18** [GarimaSingh0109/Resum-Resume#82]
Its a very basic issue but make a very big difference in UI/UX, text colors are not making contrast with their background which makes user experience bad when try to read the text.
There are a lot of thing in website which are not using a proper color scheme like footer is not matching with over all website.
Also the text of footer is very small to read, icon used in footer are very small.
Main logo size and other element in navbar are also a little bit big.
I can solve these issue very well if this issue is assign to me and make website's overall experience better.

**Comment by Mohitranag18** [comment]
I can solve this issue very well, please assign this issue to me and i will make website's user experience better.

**Comment by Prarthana-35** [comment]
Can you assign this issue to me ? I shall make the user experience better.
