### ISSUE TITLE
Add Collapsible Categories with Dropdown for Step 1 in Resume Builder

### ISSUE THREAD

**Issue by Mohitranag18** [GarimaSingh0109/Resum-Resume#835]
### Description:

Currently, the Step 1 section of the resume builder is quite large in height, making the UI appear cluttered and overwhelming for users. To improve the user experience and provide a cleaner, more intuitive interface, I propose adding collapsible categories with dropdown functionality for each main heading in Step 1.

### Feature Breakdown:

**Collapsible Categories:**

- Each category (e.g., Personal Information, Education, Experience, Skills) in Step 1 will have a dropdown arrow icon next to the main heading.
- Initially, all categories will be collapsed, showing only the main heading and dropdown icon.
- When the user clicks the dropdown arrow, the category will expand, revealing input fields for that specific section.
- Clicking the dropdown icon again will collapse the category, hiding the input elements.

**Hamburger Menu Style Functionality:**

- The dropdown functionality will resemble a hamburger menu, with sections expanding or collapsing based on user interaction.
- After the user finishes inputting details in one category, they can move to the next by collapsing the previous section and expanding the next category.

**UI/UX Enhancements:**

- The design will maintain a clean and minimal look, reducing the visual clutter of the large form.
- Transitions and animations will be smooth to ensure a seamless user experience.
- All categories will be responsive, ensuring they look good across different devices and screen sizes.

**Additional Notes:**

- This feature will improve the overall user experience by making the form easier to navigate and more user-friendly.

Screenshot for Reference:
![Screenshot 2024-10-22 at 12-50-48 HackerRank](https://github.com/user-attachments/assets/b92e6998-89f1-454f-b671-6ad273db43ab)

![Screenshot 2024-10-22 at 12-51-06 HackerRank](https://github.com/user-attachments/assets/6606884b-f94b-4e76-aa79-3405144bce3f)

**Comment by GarimaSingh0109** [comment]
@Mohitranag18 do follow color pallet
