### ISSUE TITLE
Fixing button color during hover

### ISSUE THREAD

**Issue by Pheonixrog** [GarimaSingh0109/Resum-Resume#837]
![Screenshot 2024-10-22 224427](https://github.com/user-attachments/assets/82bea082-4905-442c-a88b-b44cb5270028)
 I want to fix the color of the button during hover because it almost make the button invisible during hover

**Comment by Pheonixrog** [comment]
Please assign this task to me

**Comment by neetu20221** [comment]
Can u  please assign this issue to me.
