### ISSUE TITLE
I want to design you login page ...

### ISSUE THREAD

**Issue by PRIYANSHU1jsnshsbhs** [GarimaSingh0109/Resum-Resume#840]
![image_2024-10-22_235539661](https://github.com/user-attachments/assets/7a16e712-65e4-4cd9-ae54-0ce61abe6f27)

**Comment by PRIYANSHU1jsnshsbhs** [comment]
I also want to add responsiveness to it

**Comment by Bhupendrakumar20** [comment]
@GarimaSingh0109 kindly assign this issue to me, surely i will improve it

**Comment by PRIYANSHU1jsnshsbhs** [comment]
@GarimaSingh0109 kindly assign it to me ..
