### ISSUE TITLE
dark and light toggle 

### ISSUE THREAD

**Issue by sv410** [GarimaSingh0109/Resum-Resume#841]
![WhatsApp Image 2024-10-15 at 12 06 01 PM (1)](https://github.com/user-attachments/assets/6e229082-84ab-400e-8533-c4f493dd015a)
![WhatsApp Image 2024-10-15 at 12 05 39 PM (1)](https://github.com/user-attachments/assets/85899f88-3daa-47fb-b7e2-023808ef139f)

**Comment by VanshGarg06** [comment]
Hi! I am eager to contribute towards this issue. Please assign this issue to me. And assign this under gssoc-ext and hacktoberfest with level 2 labels, so its a request please assign this to me.
