### ISSUE TITLE
improve footer section

### ISSUE THREAD

**Issue by khushi-joshi-05** [GarimaSingh0109/Resum-Resume#842]
Issue Title: Improve Footer Section Design and Functionality

Description: The current footer section lacks visual appeal and functionality. It needs to be enhanced for better user experience. Suggestions for improvement include:

- Adding links to important pages (About, Contact, Privacy Policy, etc.).
- Improving layout with better alignment and spacing.
- Including social media icons for easy access.
- Making the footer responsive for various screen sizes.
- Ensuring consistent styling with the rest of the site.

Enhancing the footer will improve navigation and provide a more professional appearance.
@GarimaSingh0109 kindly assign this issue to me under hacktoberfest only.

**Comment by Bhupendrakumar20** [comment]
Including social media icons for easy access
Adding links to important pages (About, Contact, Privacy Policy, etc.).
Improving layout with better alignment and spacing.

@GarimaSingh0109  kindly assign this issues to me under labels

**Comment by MansiJangid** [comment]
@GarimaSingh0109 Hey!!... the footer section is still not up to the mark and the colour scheme is not going well.
Can you please assign this issue to me under the labels
