### ISSUE TITLE
Bug: Add Header to the Sign up and Login Page

### ISSUE THREAD

**Issue by MansiJangid** [GarimaSingh0109/Resum-Resume#845]
Sign-up and Login pages don't contain the header. Accessing the home and other pages directly from the signup and login pages is hard.
I will add the header to both pages which contain home and other pages link 
![Screenshot (170)](https://github.com/user-attachments/assets/65e708fe-8db1-4e23-b4e4-552e92d3bb4e)

![Screenshot (171)](https://github.com/user-attachments/assets/66213d96-18a4-4cef-a5a7-da8709d20b4c)

**Comment by umeshmunde** [comment]
I can do this can you assign me for it. I also has a good knowledge of html, css ,js. or of other things
