### ISSUE TITLE
Login Page Development

### ISSUE THREAD

**Issue by Pranathi71** [GarimaSingh0109/Resum-Resume#850]
Assige this issue to me..
I would like to develop login page
![Screenshot 2024-10-23 180006](https://github.co@GarimaSingh0109 r-attachments/assets/201bcc2b-019b-4f57-a476-c27cf8381215)
@Gari

**Comment by VanshGarg06** [comment]
Hi! I am eager to contribute towards this issue. Please assign this issue to me. And assign this under gssoc and hacktoberfest with level 2 labels as it is a time taking process, so its a request.
