### ISSUE TITLE
About page footer needs improvement

### ISSUE THREAD

**Issue by VanshGarg06** [GarimaSingh0109/Resum-Resume#857]
Footer of the about page is not looking nice and the formatting is also not that appealing for different users.
Please assign this issue to me under gssoc-ext and hacktoberfest at level 1 as the labels.
![s2](https://github.com/user-attachments/assets/f7411222-d979-4027-a81e-d50c17baae46)

**Comment by MuhammadZaid-31** [comment]
I would like to work on these ,kindly assign me the issues
