### ISSUE TITLE
About page Navbar styling 

### ISSUE THREAD

**Issue by VanshGarg06** [GarimaSingh0109/Resum-Resume#858]
As it can be seen that the navbar styling is not done and the alignment of the elements are not proper.
Please assign this issue to me under gssoc-ext and hacktoberfest with level 1.
![s1](https://github.com/user-attachments/assets/f9f08bd2-5c09-4410-b5c1-bdd341343768)

Please assign this task to me as soon as possible.
Labels:
``hacktobefest2024,gssoc-ext,level 2``

**Comment by pameladeysarkar2003** [comment]
@GarimaSingh0109 please assign the task the task to me i can contribute to it
