### ISSUE TITLE
Home button is not working on Build resume page

### ISSUE THREAD

**Issue by charrviwadhwa** [GarimaSingh0109/Resum-Resume#861]
the home button on build resume page is not working. As we are clicking on it, it is not navigating to the home page.
![Screenshot 2024-10-24 020149](https://github.com/user-attachments/assets/6f02d2ea-387c-4a28-8963-bfd798f729ca)

**Comment by charrviwadhwa** [comment]
please assign this issue to me

**Comment by umeshmunde** [comment]
I can do this can you assign me . I also has a good knowledge of html, css ,js. or of other things

**Comment by charrviwadhwa** [comment]
I would like to work on this issue

**Comment by VanshGarg06** [comment]
Hi! I am eager to contribute towards this issue . Please assign this issue to me @GarimaSingh0109  under hacktoberfest and gssoc-ext with level1 labels. @VanshGarg06

**Comment by charrviwadhwa** [comment]
Please assign this issue to me@GarimaSingh0109

**Comment by VanshGarg06** [comment]
Please assign this issue to me under hacktoberfest and gssoc-ext with necessary labels.

**Comment by charrviwadhwa** [comment]
i would like to work on this issue

**Comment by charrviwadhwa** [comment]
please assign this issue to me
