### ISSUE TITLE
Enhance CSS Styling for Progress Bars and Form Layout

### ISSUE THREAD

**Issue by NirajD04** [GarimaSingh0109/Resum-Resume#874]
The current CSS for the progress bars and form layout requires improvements to enhance user experience and visual appeal. This issue aims to address the following areas:

Progress Bar:

Improve the visibility and aesthetics of the progress bar steps.
Implement active and hover states for better interactivity.
Consider adding gradient effects to progress lines for a modern look.
Button Interactivity:

Add hover effects and scaling animations to buttons to enhance feedback when users interact with them.

Responsive Design:

Ensure the layout is fully responsive and adapts well to various screen sizes, especially on mobile devices.
Optimize the form fields and template sections for better usability.
General UI/UX Improvements:

Review spacing and layout consistency across different sections.
Apply a cohesive color scheme and font styles to improve overall design harmony.

Steps to Reproduce:
Open the application in various screen sizes.
Observe the current styles of progress bars, buttons, and form layouts.
Note the lack of interactivity and responsiveness.

Expected Outcome:
A visually appealing and interactive progress bar with clear active states.
Enhanced button hover effects for better user engagement.
A fully responsive design that maintains usability across devices.

**Comment by NirajD04** [comment]
please assign this to me under gssoc'24 extd .

**Comment by pameladeysarkar2003** [comment]
@GarimaSingh0109 please assign the task to me i can contribute to it
