### ISSUE TITLE
I want to style login page.

### ISSUE THREAD

**Issue by royvivi29** [GarimaSingh0109/Resum-Resume#878]
<img width="959" alt="image" src="https://github.com/user-attachments/assets/2ba52f9e-b8d9-4c88-b2d5-d01bcfbd9d61">

**Comment by VanshGarg06** [comment]
This issue is already been created before don't create new issues check for already created issues.

**Comment by Shalinis19137** [comment]
I really like your app and want to work on your project ,please assign this issue to me under gssoc-ext 2024
