### ISSUE TITLE
footer text is looking dull want fix them

### ISSUE THREAD

**Issue by REHAN-18** [GarimaSingh0109/Resum-Resume#927]
<img width="1370" alt="Screenshot 2024-10-29 at 5 47 17 PM" src="https://github.com/user-attachments/assets/6b7de5c4-4dee-4122-a772-3a6fab63b545">
add real social media icon hover on the footer & fix the ui 
@GarimaSingh0109 pls assign me

**Comment by Vaishnavishinde9552** [comment]
plz assign me this issue
