### ISSUE TITLE
Adding animations and hover effect to social icons

### ISSUE THREAD

**Issue by PATILYASHH** [GarimaSingh0109/Resum-Resume#931]
## Adding animations and hover effect to social icons

Social icons don't have any interesting animations or hover effect 

**Screenshot**
![image](https://github.com/user-attachments/assets/097e0360-f2aa-44e4-bcc6-42116ab43fad)

**Comment by PATILYASHH** [comment]
please assign this issue to me

**Comment by SAURABH0-7-0** [comment]
i want to work on it, please assign it to me
