### ISSUE TITLE
 Navbar links are not working on the Login page

### ISSUE THREAD

**Issue by hbSrujana** [GarimaSingh0109/Resum-Resume#935]
[Bug]: Navbar links are not working on the Login page.

Description:
On the Login page, the navbar links are not functioning as expected. When a user clicks on any element (e.g., Home, AboutUs,  Resume, SignUp, and Login), the page is not navigating to the respective section or route.

Steps to Reproduce :
1) Go to the Login page.
2) Click on any element in the navbar (e.g., Home, About).
3) Observe that the page does not navigate to the corresponding route or section.

Expected Behavior :
When a user clicks on the navbar items, the respective pages should open, or they should be redirected to the correct section.

Actual Behavior:
Clicking on any element in the navbar has no effect; the page remains on the Login page.

Screenshots (if any) :
![Screenshot 2024-10-29 225259](https://github.com/user-attachments/assets/97e0a568-cf42-4549-86a4-afac028f3c21)

Possible Solution :
1) Ensure that the links in the navbar have the correct href or to attributes pointing to valid routes.
2) If the project uses React Router, ensure that the Link component is used correctly inside the navbar.
3) Verify that the event handlers in the navbar are not blocked by JavaScript or other scripts.

Environment Details :
Browser : Chrome
Device : Desktop
OS :  Windows 11

**Comment by hbSrujana** [comment]
Hey! I'd like to work on this issue. Please assign it to me. I'm currently working on the fix and will submit a PR soon.

**Comment by hbSrujana** [comment]
@GarimaSingh0109 could you please review my PR? 😊

**Comment by Coder-Harsha-2805** [comment]
Hey! I'd like to work on this issue. Please assign it to me.
