### ISSUE TITLE
correct the "fontsize" on "build Resume" page for all buttons

### ISSUE THREAD

**Issue by Arisha2902** [GarimaSingh0109/Resum-Resume#945]
![Screenshot (31)](https://github.com/user-attachments/assets/d6b07b90-52af-499e-8b72-8b973a53df8f)

![Screenshot (32)](https://github.com/user-attachments/assets/581defd0-b233-4cf2-967f-228f460a3fe1)

![Screenshot (33)](https://github.com/user-attachments/assets/aa16dd73-7b87-478c-9cc6-b8049fc3c968)

@GarimaSingh0109 ,the font size of all the buttons on "build resume "page is very small,I can make the font size big.
plz ,assign me this issue ,as I need only one more issue for "hacktoberfest"

**Comment by annastudent2003** [comment]
@GarimaSingh0109 I would like to work on this issue. If you don't mind, can you please assign me this task?

**Comment by divcs** [comment]
I would like to work on this issue. Please assign it to me.
