### ISSUE TITLE
Open for Contributors: Add Resume ATS Score Finder

### ISSUE THREAD

**Issue by Vaibhav22p-qw** [GarimaSingh0109/Resum-Resume#95]
Looking for contributors to implement a Resume ATS Score Finder feature. This tool will analyze resumes for ATS compatibility, score them based on keyword matching, formatting, and structure, and provide actionable feedback for improvement. It should support both file uploads and text input.

**Comment by Charul00** [comment]
can you please assign to me

**Comment by Vaibhav22p-qw** [comment]
Why, we assign you?

**Comment by Charul00** [comment]
because i am interested in this 
and have little bit experience how to do this 
and i learn the how ats score system work

**Comment by Vaibhav22p-qw** [comment]
@Charul00  Deadline: Today (Before 20:00PM)

**Comment by Vaibhav22p-qw** [comment]
so, Can i assign you

**Comment by KhushieBrahma** [comment]
I can do the task. Kindly assign this task to me.

**Comment by Charul00** [comment]
> so, Can i assign you

yeah sure please assign me

**Comment by BhavikaPachauri** [comment]
I am interest this

**Comment by Bhumika-00** [comment]
i am intrested.

**Comment by adarshsingh0103** [comment]
@Vaibhav22p-qw  Can you please! assign me to work on this issue.

**Comment by faheem2312** [comment]
Hey there, Can you assign me this issue!!

**Comment by momithalasya** [comment]
Consider assigning this task to me 
because,
I have little knowledge about regular expressions, text processing and I have basic programming skills required
this will help me learn more and develop my skills

**Comment by tobiasrahul** [comment]
Please assign me this issue

**Comment by momithalasya** [comment]
@Vaibhav22p-qw Thanks for assigning this to me
I will try to complete this asap

**Comment by momithalasya** [comment]
@GarimaSingh0109 Thanks for merging my PR!!!
