### ISSUE TITLE
Footer enhancement

### ISSUE THREAD

**Issue by saatvika07** [GarimaSingh0109/Resum-Resume#960]
@GarimaSingh0109 I can make the footer look more appealing 

Please find attached and do add labels of gssoc, gssoc-ext, hackoberfest etc.

Thank You!
<img width="960" alt="resum resume footer" src="https://github.com/user-attachments/assets/ae0b27f3-36d4-4e06-9c42-e3e4abf12632">

**Comment by Mohdsaad21-6** [comment]
i want to work on footer . so make it more attractive

**Comment by saatvika07** [comment]
The issue is not yet assigned to me
