### ISSUE TITLE
Added Scroll-Up Button for Improved Navigation on the Main Page

### ISSUE THREAD

**Issue by ak-0283** [GarimaSingh0109/Resum-Resume#977]
As a contributor to GirlScript Summer of Code 2024, I noticed the absence of a scroll-up button on the Start Writing page, which made navigation challenging, especially on longer posts. To enhance user experience and streamline content creation, I implemented a scroll-up button, allowing users to quickly return to the top of the page. This feature improves accessibility and usability, making the page more intuitive and user-friendly.

**View Bug**

![Screenshot 2024-11-02 194441](https://github.com/user-attachments/assets/4a92d330-2b66-412d-b6e3-db7c306763b8)

**Comment by ak-0283** [comment]
Please assign me this issue @GarimaSingh0109

**Comment by veerendra17788** [comment]
please assign to me i can do that
