### ISSUE TITLE
add cookies to website

### ISSUE THREAD

**Issue by samiksha1618** [GarimaSingh0109/Resum-Resume#979]
Cookies help create a personalized experience by remembering if a user has already submitted feedback, so they don’t get asked to do it again. This makes their visit smoother. They also enhance user engagement because, by knowing when someone has given feedback, you can send more relevant follow-up messages. Additionally, cookies track how often users interact with the feedback form, giving you useful information about their behavior and preferences. This insight can help you understand what users want and improve the overall experience.

**Comment by vaniasetia** [comment]
I’d like to request assignment of this issue, which involves adding functionality for setting and retrieving cookies in JavaScript. I’ve outlined a solution to handle cookies, including functions for setting cookies with specified expiration times, paths, and the ability to retrieve values by cookie name.
My solution would provide a clear approach for managing cookies, with attention to security aspects like "Secure" and "HttpOnly" attributes where applicable. If assigned, I will ensure the code is well-documented and thoroughly tested.
Thank you for considering my request!
