### ISSUE TITLE
Footer Adjustment and Rating Feature for Resume Builder Website

### ISSUE THREAD

**Issue by keerthi070** [GarimaSingh0109/Resum-Resume#982]
@GarimaSingh0109 the footer so it stays fixed at the bottom of the page. Additionally, could we add a rating feature to the resume builder website? This would allow users to give feedback, helping us improve the tool.
Please assign me to do it.

![Screenshot 2024-11-03 184054](https://github.com/user-attachments/assets/1e33157e-686e-4152-9065-8401d1a620c1)

Thank you.

**Comment by veerendra17788** [comment]
please assign to me i can do that
